# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: killme_PL # jekyll-seo-tag > Owners twitter username
author: pgum # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Piotr Jacek Gumulka # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/killme_PL
    - https://www.linkedin.com/in/piotr-gumulka
    - https://github.com/pgum
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Warsaw # Timezone for blog posts and alike


# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values


# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
theme: alembic-jekyll-theme
title: pgum thinking space
email: pjgumulka@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/blogtest" # the subpath of your site, e.g. /blog
url: "http://pgum.github.io" # the base hostname & protocol for your site
github_username:  pgum

github:
  repository_name: blogtest
  project_tagline: blogtest is test for blog

# Build settings
markdown: kramdown

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Elements
  url: /elements/
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: Search
  url: /search/
- title: Fork Alembic
  url: https://github.com/daviddarnes/alembic

navigation_footer:
- title: Created by David Darnes
  url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/killme_PL
  LinkedIn: https://www.linkedin.com/in/piotr-gumulka
  GitHub: https://github.com/pgum
  link: https://pgum.github.io
  RSS: /feed.xml


collections:
  notes:
    output: true
  roles:
    output: true
  scenarios:
    output: true

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji